// Datos del catálogo Straven — generado a partir de data/productos.csv
const PRODUCTS = [
  {
    "id": "bermuda_levis",
    "name": "Bermudas Levi's",
    "category": "Bottom",
    "brandLogo": "levis.webp",
    "promo": "",
    "priceRetail": 349.0,
    "priceDozen1": 331.55,
    "priceDozen2": 314.1,
    "priceDozen3": 296.65,
    "mixedQty": 25,
    "mixedPrice": 279.0,
    "folder": "bermuda_levis",
    "images": [
      "bermuda_levis_1.jpg",
      "bermuda_levis_2.jpg",
      "bermuda_levis_3.jpg",
      "bermuda_levis_4.jpg",
      "bermuda_levis_5.jpg",
      "bermuda_levis_6.jpg"
    ]
  },
  {
    "id": "calcetas",
    "name": "Calcetas",
    "category": "Otros",
    "brandLogo": "multimarca.webp",
    "promo": "",
    "priceRetail": 14.0,
    "priceDozen1": 13.3,
    "priceDozen2": 12.6,
    "priceDozen3": 11.9,
    "mixedQty": 500,
    "mixedPrice": 11.0,
    "folder": "calcetas",
    "images": [
      "calcetas_1.jpg",
      "calcetas_2.jpg",
      "calcetas_3.jpg",
      "calcetas_4.jpg",
      "calcetas_5.jpg",
      "calcetas_6.jpg",
      "calcetas_7.jpg",
      "calcetas_8.jpg",
      "calcetas_9.jpg",
      "calcetas_10.jpg"
    ]
  },
  {
    "id": "camisa_casual_levis",
    "name": "Camisa Casual Levi's",
    "category": "Camisa",
    "brandLogo": "levis.webp",
    "promo": "2x1",
    "priceRetail": 699.0,
    "priceDozen1": 664.05,
    "priceDozen2": 629.1,
    "priceDozen3": 594.15,
    "mixedQty": 25,
    "mixedPrice": 559.2,
    "folder": "camisa_casual_levis",
    "images": [
      "camisa_casual_levis_1.jpg",
      "camisa_casual_levis_2.jpg",
      "camisa_casual_levis_3.jpg",
      "camisa_casual_levis_4.jpg",
      "camisa_casual_levis_5.jpg",
      "camisa_casual_levis_6.jpg"
    ]
  },
  {
    "id": "camisa_franela_levis",
    "name": "Camisa de Franela Levi's",
    "category": "Camisa",
    "brandLogo": "levis.webp",
    "promo": "",
    "priceRetail": 369.0,
    "priceDozen1": 350.55,
    "priceDozen2": 332.1,
    "priceDozen3": 313.65,
    "mixedQty": 25,
    "mixedPrice": 299.0,
    "folder": "camisa_franela_levis",
    "images": [
      "camisa_franela_levis_1.jpg",
      "camisa_franela_levis_2.jpg",
      "camisa_franela_levis_3.jpg",
      "camisa_franela_levis_4.jpg",
      "camisa_franela_levis_5.jpg",
      "camisa_franela_levis_6.jpg"
    ]
  },
  {
    "id": "playera_mezclilla_levis",
    "name": "Camisa de Mezclilla Levi's",
    "category": "Camisa",
    "brandLogo": "levis.webp",
    "promo": "",
    "priceRetail": 399.0,
    "priceDozen1": 379.05,
    "priceDozen2": 359.1,
    "priceDozen3": 339.15,
    "mixedQty": 25,
    "mixedPrice": 320.0,
    "folder": "playera_mezclilla_levis",
    "images": [
      "playera_mezclilla_levis_1.jpg",
      "playera_mezclilla_levis_2.jpg",
      "playera_mezclilla_levis_3.jpg",
      "playera_mezclilla_levis_4.jpg"
    ]
  },
  {
    "id": "chaleco_columbia",
    "name": "Chaleca Columbia",
    "category": "Otros",
    "brandLogo": "columbia.webp",
    "promo": "",
    "priceRetail": 335.0,
    "priceDozen1": 318.25,
    "priceDozen2": 301.5,
    "priceDozen3": 284.75,
    "mixedQty": 25,
    "mixedPrice": 270.0,
    "folder": "chaleco_columbia",
    "images": [
      "chaleco_columbia_1.jpg"
    ]
  },
  {
    "id": "chamarra_adidas",
    "name": "Chamarra Adidas",
    "category": "Sudadera",
    "brandLogo": "adidas.webp",
    "promo": "",
    "priceRetail": 399.0,
    "priceDozen1": 379.05,
    "priceDozen2": 359.1,
    "priceDozen3": 339.15,
    "mixedQty": 25,
    "mixedPrice": 319.0,
    "folder": "chamarra_adidas",
    "images": [
      "chamarra_adidas_1.jpg",
      "chamarra_adidas_2.jpg"
    ]
  },
  {
    "id": "chamarra_polar_columbia",
    "name": "Chamarra Polar Columbia",
    "category": "Sudadera",
    "brandLogo": "columbia.webp",
    "promo": "",
    "priceRetail": 335.0,
    "priceDozen1": 318.25,
    "priceDozen2": 301.5,
    "priceDozen3": 284.75,
    "mixedQty": 25,
    "mixedPrice": 270.0,
    "folder": "chamarra_polar_columbia",
    "images": [
      "chamarra_polar_columbia_1.jpg",
      "chamarra_polar_columbia_2.jpg",
      "chamarra_polar_columbia_3.jpg",
      "chamarra_polar_columbia_4.jpg"
    ]
  },
  {
    "id": "gorra_puma_ch",
    "name": "Gorra Básica Puma",
    "category": "Gorra",
    "brandLogo": "puma.webp",
    "promo": "",
    "priceRetail": 220.0,
    "priceDozen1": 209.0,
    "priceDozen2": 198.0,
    "priceDozen3": 187.0,
    "mixedQty": 30,
    "mixedPrice": 182.0,
    "folder": "gorra_puma_ch",
    "images": [
      "gorra_puma_ch_1.jpg",
      "gorra_puma_ch_2.jpg",
      "gorra_puma_ch_3.jpg",
      "gorra_puma_ch_4.jpg",
      "gorra_puma_ch_5.jpg"
    ]
  },
  {
    "id": "gorra_puma_m",
    "name": "Gorra Media Puma",
    "category": "Gorra",
    "brandLogo": "puma.webp",
    "promo": "",
    "priceRetail": 249.0,
    "priceDozen1": 236.55,
    "priceDozen2": 224.1,
    "priceDozen3": 211.65,
    "mixedQty": 30,
    "mixedPrice": 199.0,
    "folder": "gorra_puma_m",
    "images": [
      "gorra_puma_m_1.jpg",
      "gorra_puma_m_2.jpg"
    ]
  },
  {
    "id": "gorra_new_era_ch",
    "name": "Gorra New Era Básica",
    "category": "Gorra",
    "brandLogo": "puma.webp",
    "promo": "",
    "priceRetail": 299.0,
    "priceDozen1": 284.05,
    "priceDozen2": 269.1,
    "priceDozen3": 254.15,
    "mixedQty": 25,
    "mixedPrice": 245.0,
    "folder": "gorra_new_era_ch",
    "images": [
      "gorra_new_era_ch_1.jpg",
      "gorra_new_era_ch_2.jpg",
      "gorra_new_era_ch_3.jpg",
      "gorra_new_era_ch_4.jpg",
      "gorra_new_era_ch_5.jpg"
    ]
  },
  {
    "id": "gorra_new_era_m",
    "name": "Gorra New Era Media",
    "category": "Gorra",
    "brandLogo": "puma.webp",
    "promo": "",
    "priceRetail": 329.0,
    "priceDozen1": 312.55,
    "priceDozen2": 296.1,
    "priceDozen3": 279.65,
    "mixedQty": 25,
    "mixedPrice": 265.0,
    "folder": "gorra_new_era_m",
    "images": [
      "gorra_new_era_m_1.jpg",
      "gorra_new_era_m_2.jpg",
      "gorra_new_era_m_3.jpg",
      "gorra_new_era_m_4.jpg",
      "gorra_new_era_m_5.jpg",
      "gorra_new_era_m_6.jpg"
    ]
  },
  {
    "id": "gorra_new_era_p",
    "name": "Gorra New Era Premium",
    "category": "Gorra",
    "brandLogo": "puma.webp",
    "promo": "",
    "priceRetail": 399.0,
    "priceDozen1": 379.05,
    "priceDozen2": 359.1,
    "priceDozen3": 339.15,
    "mixedQty": 25,
    "mixedPrice": 320.0,
    "folder": "gorra_new_era_p",
    "images": [
      "gorra_new_era_p_1.jpg",
      "gorra_new_era_p_2.jpg",
      "gorra_new_era_p_3.jpg",
      "gorra_new_era_p_4.jpg",
      "gorra_new_era_p_5.jpg",
      "gorra_new_era_p_6.jpg"
    ]
  },
  {
    "id": "gorra_puma_p",
    "name": "Gorra Premium Puma",
    "category": "Gorra",
    "brandLogo": "puma.webp",
    "promo": "",
    "priceRetail": 329.0,
    "priceDozen1": 312.55,
    "priceDozen2": 296.1,
    "priceDozen3": 279.65,
    "mixedQty": 30,
    "mixedPrice": 265.0,
    "folder": "gorra_puma_p",
    "images": [
      "gorra_puma_p_1.jpg",
      "gorra_puma_p_2.jpg",
      "gorra_puma_p_3.jpg",
      "gorra_puma_p_4.jpg",
      "gorra_puma_p_5.jpg",
      "gorra_puma_p_6.jpg"
    ]
  },
  {
    "id": "jeans_levis",
    "name": "Jeans Levi's",
    "category": "Bottom",
    "brandLogo": "levis.webp",
    "promo": "2x1",
    "priceRetail": 799.0,
    "priceDozen1": 759.05,
    "priceDozen2": 719.1,
    "priceDozen3": 679.15,
    "mixedQty": 20,
    "mixedPrice": 639.2,
    "folder": "jeans_levis",
    "images": [
      "jeans_levis_1.jpg",
      "jeans_levis_2.jpg",
      "jeans_levis_3.jpg",
      "jeans_levis_4.jpg",
      "jeans_levis_5.jpg",
      "jeans_levis_6.jpg"
    ]
  },
  {
    "id": "leggins_athleta",
    "name": "Leggins Athleta",
    "category": "Bottom",
    "brandLogo": "athleta.webp",
    "promo": "2x1",
    "priceRetail": 299.0,
    "priceDozen1": 284.05,
    "priceDozen2": 269.1,
    "priceDozen3": 254.15,
    "mixedQty": 50,
    "mixedPrice": 239.2,
    "folder": "leggins_athleta",
    "images": [
      "leggins_athleta_1.jpg",
      "leggins_athleta_2.jpg",
      "leggins_athleta_3.jpg",
      "leggins_athleta_4.jpg",
      "leggins_athleta_5.jpg",
      "leggins_athleta_6.jpg",
      "leggins_athleta_7.jpg",
      "leggins_athleta_8.jpg",
      "leggins_athleta_9.jpg",
      "leggins_athleta_10.jpg",
      "leggins_athleta_11.jpg",
      "leggins_athleta_12.jpg",
      "leggins_athleta_13.jpg",
      "leggins_athleta_14.jpg"
    ]
  },
  {
    "id": "leggins_under",
    "name": "Leggins Under Armour",
    "category": "Bottom",
    "brandLogo": "under.webp",
    "promo": "",
    "priceRetail": 185.0,
    "priceDozen1": 175.75,
    "priceDozen2": 166.5,
    "priceDozen3": 157.25,
    "mixedQty": 50,
    "mixedPrice": 145.0,
    "folder": "leggins_under",
    "images": [
      "leggins_under_1.jpg",
      "leggins_under_2.jpg",
      "leggins_under_3.jpg",
      "leggins_under_4.jpg",
      "leggins_under_5.jpg",
      "leggins_under_6.jpg"
    ]
  },
  {
    "id": "mascarillas",
    "name": "Mascarillas",
    "category": "Belleza",
    "brandLogo": "freeman.webp",
    "promo": "",
    "priceRetail": 10.0,
    "priceDozen1": 9.5,
    "priceDozen2": 9.0,
    "priceDozen3": 8.5,
    "mixedQty": 500,
    "mixedPrice": 8.0,
    "folder": "mascarillas",
    "images": [
      "mascarillas_1.jpg",
      "mascarillas_2.jpg",
      "mascarillas_3.jpg",
      "mascarillas_4.jpg",
      "mascarillas_5.jpg",
      "mascarillas_6.jpg"
    ]
  },
  {
    "id": "mochila_puma",
    "name": "Mochila Puma",
    "category": "Mochila",
    "brandLogo": "puma.webp",
    "promo": "",
    "priceRetail": 269.0,
    "priceDozen1": 255.55,
    "priceDozen2": 242.1,
    "priceDozen3": 228.65,
    "mixedQty": 25,
    "mixedPrice": 215.0,
    "folder": "mochila_puma",
    "images": [
      "mochila_puma_1.jpg",
      "mochila_puma_2.jpg",
      "mochila_puma_3.jpg",
      "mochila_puma_4.jpg",
      "mochila_puma_5.jpg",
      "mochila_puma_6.jpg",
      "mochila_puma_7.jpg",
      "mochila_puma_8.jpg",
      "mochila_puma_9.jpg",
      "mochila_puma_10.jpg"
    ]
  },
  {
    "id": "playera_columbia",
    "name": "Playera Columbia",
    "category": "Playera",
    "brandLogo": "columbia.webp",
    "promo": "",
    "priceRetail": 290.0,
    "priceDozen1": 275.5,
    "priceDozen2": 261.0,
    "priceDozen3": 246.5,
    "mixedQty": 25,
    "mixedPrice": 230.0,
    "folder": "playera_columbia",
    "images": [
      "playera_columbia_1.jpg",
      "playera_columbia_2.jpg",
      "playera_columbia_3.jpg",
      "playera_columbia_4.jpg",
      "playera_columbia_5.jpg",
      "playera_columbia_6.jpg"
    ]
  },
  {
    "id": "playera_deportiva_adidas",
    "name": "Playera Deportiva Adidas",
    "category": "Playera",
    "brandLogo": "adidas.webp",
    "promo": "",
    "priceRetail": 265.0,
    "priceDozen1": 251.75,
    "priceDozen2": 238.5,
    "priceDozen3": 225.25,
    "mixedQty": 25,
    "mixedPrice": 212.0,
    "folder": "playera_deportiva_adidas",
    "images": [
      "playera_deportiva_adidas_1.jpg",
      "playera_deportiva_adidas_2.jpg",
      "playera_deportiva_adidas_3.jpg",
      "playera_deportiva_adidas_4.jpg",
      "playera_deportiva_adidas_5.jpg",
      "playera_deportiva_adidas_6.jpg"
    ]
  },
  {
    "id": "playera_deportiva_manga_larga_columbia",
    "name": "Playera Deportiva Manga Larga Columbia",
    "category": "Playera",
    "brandLogo": "columbia.webp",
    "promo": "",
    "priceRetail": 335.0,
    "priceDozen1": 318.25,
    "priceDozen2": 301.5,
    "priceDozen3": 284.75,
    "mixedQty": 25,
    "mixedPrice": 270.0,
    "folder": "playera_deportiva_manga_larga_columbia",
    "images": [
      "playera_deportiva_manga_larga_columbia_1.jpg",
      "playera_deportiva_manga_larga_columbia_2.jpg",
      "playera_deportiva_manga_larga_columbia_3.jpg",
      "playera_deportiva_manga_larga_columbia_4.jpg"
    ]
  },
  {
    "id": "playera_futbol_puma",
    "name": "Playera Futbol Puma",
    "category": "Playera",
    "brandLogo": "puma.webp",
    "promo": "",
    "priceRetail": 329.0,
    "priceDozen1": 312.55,
    "priceDozen2": 296.1,
    "priceDozen3": 279.65,
    "mixedQty": 25,
    "mixedPrice": 259.0,
    "folder": "playera_futbol_puma",
    "images": [
      "playera_futbol_puma_1.jpg",
      "playera_futbol_puma_2.jpg",
      "playera_futbol_puma_3.jpg",
      "playera_futbol_puma_4.jpg",
      "playera_futbol_puma_5.jpg",
      "playera_futbol_puma_6.jpg"
    ]
  },
  {
    "id": "playera_levis",
    "name": "Playera Levi's",
    "category": "Playera",
    "brandLogo": "levis.webp",
    "promo": "",
    "priceRetail": 265.0,
    "priceDozen1": 251.75,
    "priceDozen2": 238.5,
    "priceDozen3": 225.25,
    "mixedQty": 40,
    "mixedPrice": 210.0,
    "folder": "playera_levis",
    "images": [
      "playera_levis_1.jpg",
      "playera_levis_2.jpg",
      "playera_levis_3.jpg",
      "playera_levis_4.jpg"
    ]
  },
  {
    "id": "playera_polo_levis",
    "name": "Playera Polo Levi's",
    "category": "Playera",
    "brandLogo": "levis.webp",
    "promo": "",
    "priceRetail": 340.0,
    "priceDozen1": 323.0,
    "priceDozen2": 306.0,
    "priceDozen3": 289.0,
    "mixedQty": 25,
    "mixedPrice": 275.0,
    "folder": "playera_polo_levis",
    "images": [
      "playera_polo_levis_1.jpg",
      "playera_polo_levis_2.jpg",
      "playera_polo_levis_3.jpg",
      "playera_polo_levis_4.jpg",
      "playera_polo_levis_5.jpg",
      "playera_polo_levis_6.jpg"
    ]
  },
  {
    "id": "playera_polo",
    "name": "Playera Polo Ralph Lauren",
    "category": "Playera",
    "brandLogo": "polo.webp",
    "promo": "",
    "priceRetail": 599.0,
    "priceDozen1": 569.05,
    "priceDozen2": 539.1,
    "priceDozen3": 509.15,
    "mixedQty": 25,
    "mixedPrice": 479.2,
    "folder": "playera_polo",
    "images": [
      "playera_polo_1.jpg",
      "playera_polo_2.jpg",
      "playera_polo_3.jpg",
      "playera_polo_4.jpg",
      "playera_polo_5.jpg",
      "playera_polo_6.jpg",
      "playera_polo_7.jpg",
      "playera_polo_8.jpg",
      "playera_polo_9.jpg",
      "playera_polo_10.jpg"
    ]
  },
  {
    "id": "playera_tommy_hilfiguer",
    "name": "Playera Tommy Hilfiguer",
    "category": "Playera",
    "brandLogo": "tommy.webp",
    "promo": "",
    "priceRetail": 599.0,
    "priceDozen1": 569.05,
    "priceDozen2": 539.1,
    "priceDozen3": 509.15,
    "mixedQty": 25,
    "mixedPrice": 479.2,
    "folder": "playera_tommy_hilfiguer",
    "images": [
      "playera_tommy_hilfiguer_1.jpg",
      "playera_tommy_hilfiguer_2.jpg",
      "playera_tommy_hilfiguer_3.jpg",
      "playera_tommy_hilfiguer_4.jpg",
      "playera_tommy_hilfiguer_5.jpg",
      "playera_tommy_hilfiguer_6.jpg",
      "playera_tommy_hilfiguer_7.jpg",
      "playera_tommy_hilfiguer_8.jpg",
      "playera_tommy_hilfiguer_9.jpg",
      "playera_tommy_hilfiguer_10.jpg",
      "playera_tommy_hilfiguer_11.jpg"
    ]
  },
  {
    "id": "shampoo",
    "name": "Shampoo",
    "category": "Belleza",
    "brandLogo": "ogx.webp",
    "promo": "2x1",
    "priceRetail": 170.0,
    "priceDozen1": 161.5,
    "priceDozen2": 153.0,
    "priceDozen3": 144.5,
    "mixedQty": 100,
    "mixedPrice": 136.0,
    "folder": "shampoo",
    "images": [
      "shampoo_1.jpg",
      "shampoo_2.jpg",
      "shampoo_3.jpg",
      "shampoo_4.jpg",
      "shampoo_5.jpg",
      "shampoo_6.jpg",
      "shampoo_7.jpg",
      "shampoo_8.jpg",
      "shampoo_9.jpg",
      "shampoo_10.jpg",
      "shampoo_11.jpg",
      "shampoo_12.jpg",
      "shampoo_13.jpg",
      "shampoo_14.jpg",
      "shampoo_15.jpg",
      "shampoo_16.jpg",
      "shampoo_17.jpg",
      "shampoo_18.jpg"
    ]
  },
  {
    "id": "shorts_levis",
    "name": "Shorts Levi's",
    "category": "Bottom",
    "brandLogo": "levis.webp",
    "promo": "",
    "priceRetail": 369.0,
    "priceDozen1": 350.55,
    "priceDozen2": 332.1,
    "priceDozen3": 313.65,
    "mixedQty": 25,
    "mixedPrice": 299.0,
    "folder": "shorts_levis",
    "images": [
      "shorts_levis_1.jpg",
      "shorts_levis_2.jpg",
      "shorts_levis_3.jpg"
    ]
  },
  {
    "id": "sudadera_columbia",
    "name": "Sudadera Columbia",
    "category": "Sudadera",
    "brandLogo": "columbia.webp",
    "promo": "",
    "priceRetail": 385.0,
    "priceDozen1": 365.75,
    "priceDozen2": 346.5,
    "priceDozen3": 327.25,
    "mixedQty": 25,
    "mixedPrice": 310.0,
    "folder": "sudadera_columbia",
    "images": [
      "sudadera_columbia_1.jpg",
      "sudadera_columbia_2.jpg",
      "sudadera_columbia_3.jpg",
      "sudadera_columbia_4.jpg",
      "sudadera_columbia_5.jpg",
      "sudadera_columbia_6.jpg"
    ]
  },
  {
    "id": "sudadera_guess",
    "name": "Sudadera Guess",
    "category": "Sudadera",
    "brandLogo": "guess.webp",
    "promo": "",
    "priceRetail": 180.0,
    "priceDozen1": 171.0,
    "priceDozen2": 162.0,
    "priceDozen3": 153.0,
    "mixedQty": 50,
    "mixedPrice": 145.0,
    "folder": "sudadera_guess",
    "images": [
      "sudadera_guess_1.jpg",
      "sudadera_guess_2.jpg",
      "sudadera_guess_3.jpg",
      "sudadera_guess_4.jpg",
      "sudadera_guess_5.jpg",
      "sudadera_guess_6.jpg",
      "sudadera_guess_7.jpg",
      "sudadera_guess_8.jpg",
      "sudadera_guess_9.jpg",
      "sudadera_guess_10.jpg",
      "sudadera_guess_11.jpg",
      "sudadera_guess_12.jpg",
      "sudadera_guess_13.jpg",
      "sudadera_guess_14.jpg",
      "sudadera_guess_15.jpg",
      "sudadera_guess_16.jpg",
      "sudadera_guess_17.jpg",
      "sudadera_guess_18.jpg",
      "sudadera_guess_19.jpg",
      "sudadera_guess_20.jpg",
      "sudadera_guess_21.jpg",
      "sudadera_guess_22.jpg",
      "sudadera_guess_23.jpg",
      "sudadera_guess_24.jpg",
      "sudadera_guess_25.jpg"
    ]
  },
  {
    "id": "sudadera_under",
    "name": "Sudadera Under",
    "category": "Sudadera",
    "brandLogo": "under.webp",
    "promo": "",
    "priceRetail": 399.0,
    "priceDozen1": 379.05,
    "priceDozen2": 359.1,
    "priceDozen3": 339.15,
    "mixedQty": 20,
    "mixedPrice": 319.0,
    "folder": "sudadera_under",
    "images": [
      "sudadera_under_1.jpg",
      "sudadera_under_2.jpg",
      "sudadera_under_3.jpg"
    ]
  },
  {
    "id": "tenis_brand",
    "name": "Tenis BrandBlack",
    "category": "Tenis",
    "brandLogo": "brandblack.webp",
    "promo": "2x1",
    "priceRetail": 1399.0,
    "priceDozen1": 1329.05,
    "priceDozen2": 1259.1,
    "priceDozen3": 1189.15,
    "mixedQty": 12,
    "mixedPrice": 1119.2,
    "folder": "tenis_brand",
    "images": [
      "tenis_brand_1.jpg",
      "tenis_brand_2.jpg",
      "tenis_brand_3.jpg",
      "tenis_brand_4.jpg",
      "tenis_brand_5.jpg",
      "tenis_brand_6.jpg",
      "tenis_brand_7.jpg",
      "tenis_brand_8.jpg",
      "tenis_brand_9.jpg",
      "tenis_brand_10.jpg",
      "tenis_brand_11.jpg",
      "tenis_brand_12.jpg",
      "tenis_brand_13.jpg",
      "tenis_brand_14.jpg",
      "tenis_brand_15.jpg",
      "tenis_brand_16.jpg",
      "tenis_brand_17.jpg",
      "tenis_brand_18.jpg",
      "tenis_brand_19.jpg"
    ]
  },
  {
    "id": "tenis_nike",
    "name": "Tenis Nike",
    "category": "Tenis",
    "brandLogo": "nike.webp",
    "promo": "2x1",
    "priceRetail": 2249.0,
    "priceDozen1": 2136.55,
    "priceDozen2": 2024.1,
    "priceDozen3": 1911.65,
    "mixedQty": 8,
    "mixedPrice": 1799.2,
    "folder": "tenis_nike",
    "images": [
      "tenis_nike_1.jpg",
      "tenis_nike_2.jpg",
      "tenis_nike_3.jpg",
      "tenis_nike_4.jpg",
      "tenis_nike_5.jpg",
      "tenis_nike_6.jpg",
      "tenis_nike_7.jpg",
      "tenis_nike_8.jpg"
    ]
  },
  {
    "id": "tenis_puma",
    "name": "Tenis puma",
    "category": "Tenis",
    "brandLogo": "puma.webp",
    "promo": "2x1",
    "priceRetail": 1749.0,
    "priceDozen1": 1661.55,
    "priceDozen2": 1574.1,
    "priceDozen3": 1486.65,
    "mixedQty": 12,
    "mixedPrice": 1399.2,
    "folder": "tenis_puma",
    "images": [
      "tenis_puma_1.jpg",
      "tenis_puma_2.jpg",
      "tenis_puma_3.jpg",
      "tenis_puma_4.jpg",
      "tenis_puma_5.jpg",
      "tenis_puma_6.jpg",
      "tenis_puma_7.jpg",
      "tenis_puma_8.jpg",
      "tenis_puma_9.jpg",
      "tenis_puma_10.jpg",
      "tenis_puma_11.jpg",
      "tenis_puma_12.jpg",
      "tenis_puma_13.jpg",
      "tenis_puma_14.jpg",
      "tenis_puma_15.jpg",
      "tenis_puma_16.jpg",
      "tenis_puma_17.jpg",
      "tenis_puma_18.jpg",
      "tenis_puma_19.jpg"
    ]
  },
  {
    "id": "tenis_reebok",
    "name": "Tenis Reebok",
    "category": "Tenis",
    "brandLogo": "reebok.webp",
    "promo": "2x1",
    "priceRetail": 1499.0,
    "priceDozen1": 1424.05,
    "priceDozen2": 1349.1,
    "priceDozen3": 1274.15,
    "mixedQty": 12,
    "mixedPrice": 1199.2,
    "folder": "tenis_reebok",
    "images": [
      "tenis_reebok_1.jpg",
      "tenis_reebok_2.jpg",
      "tenis_reebok_3.jpg",
      "tenis_reebok_4.jpg",
      "tenis_reebok_5.jpg",
      "tenis_reebok_6.jpg",
      "tenis_reebok_7.jpg",
      "tenis_reebok_8.jpg",
      "tenis_reebok_9.jpg",
      "tenis_reebok_10.jpg",
      "tenis_reebok_11.jpg",
      "tenis_reebok_12.jpg",
      "tenis_reebok_13.jpg",
      "tenis_reebok_14.jpg",
      "tenis_reebok_15.jpg",
      "tenis_reebok_16.jpg",
      "tenis_reebok_17.jpg",
      "tenis_reebok_18.jpg",
      "tenis_reebok_19.jpg",
      "tenis_reebok_20.jpg",
      "tenis_reebok_21.jpg",
      "tenis_reebok_22.jpg"
    ]
  }
];
